/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef PHIASYMMETRYPDF
#define PHIASYMMETRYPDF

#include "RooAbsPdf.h"
#include "RooHSEventsPDF.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class PhiAsymmetryPDF : public HS::FIT::RooHSEventsPDF {
public:
  PhiAsymmetryPDF() {} ; 
  PhiAsymmetryPDF(const char *name, const char *title,
	      RooAbsReal& _Phi,
	      RooAbsReal& _A,
	      RooAbsReal& _B);
  PhiAsymmetryPDF(const PhiAsymmetryPDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new PhiAsymmetryPDF(*this,newname); }
  inline virtual ~PhiAsymmetryPDF() { }

protected:

  RooRealProxy Phi ;
  RooRealProxy A ;
  RooRealProxy B ;
  
  Double_t evaluateData() const final;
  Double_t evaluateMC(const vector<Float_t> *vars,const  vector<Int_t> *cats) const final;
  void MakeSets();

private:

  ClassDef(PhiAsymmetryPDF,1) // Your description goes here...
};
 
#endif
