/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef PHIASYMMETRYPDFVAR
#define PHIASYMMETRYPDFVAR

#include "RooAbsPdf.h"
#include "RooHSEventsPDF.h"
#include "RooRealProxy.h"
#include "RooListProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooFormulaVar.h"
 
class PhiAsymmetryPDFVar : public HS::FIT::RooHSEventsPDF {
public:
  PhiAsymmetryPDFVar() {} ; 
  PhiAsymmetryPDFVar(const char *name, const char *title,
	      RooAbsReal& _Phi,
	      RooAbsReal& _A,
		     RooAbsReal& _B,
	      RooAbsReal& _COS2,
	      RooAbsReal& _SIN2);
  PhiAsymmetryPDFVar(const PhiAsymmetryPDFVar& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new PhiAsymmetryPDFVar(*this,newname); }
  inline virtual ~PhiAsymmetryPDFVar() { }

protected:

  RooRealProxy Phi ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy COS2 ;
  RooRealProxy SIN2 ;

  vector<RooRealProxy*> fArgsV;
  vector<RooRealProxy*> fArgs;
  RooListProxy fArgsL;
  Double_t evaluate() const ;
  Double_t evaluateMC(const vector<Float_t> *vars,const  vector<Int_t> *cats) const ;
  void MakeSets();

private:

  ClassDef(PhiAsymmetryPDFVar,1) // Your description goes here...
};
 
#endif
