/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef PHITHASYMMETRYPDF
#define PHITHASYMMETRYPDF

#include "RooAbsPdf.h"
#include "RooHSEventsPDF.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class PhiThAsymmetryPDF : public HS::FIT::RooHSEventsPDF {
public:
  PhiThAsymmetryPDF() {} ; 
  PhiThAsymmetryPDF(const char *name, const char *title,
	      RooAbsReal& _Phi,
	      RooAbsReal& _Theta,
	      RooAbsReal& _A,
	      RooAbsReal& _B);
  PhiThAsymmetryPDF(const PhiThAsymmetryPDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new PhiThAsymmetryPDF(*this,newname); }
  inline virtual ~PhiThAsymmetryPDF() { }

protected:

  RooRealProxy Phi ;
  RooRealProxy Theta ;
  RooRealProxy A ;
  RooRealProxy B ;
  
  Double_t evaluate() const ;
  Double_t evaluateMC(const vector<Float_t> *vars,const  vector<Int_t> *cats) const ;
  void MakeSets();

private:

  ClassDef(PhiThAsymmetryPDF,1) // Your description goes here...
};
 
#endif
