// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /home/dglazier/annika/HASPECT6/hsfit/sPlot.h;
#pragma link C++ defined_in "/home/dglazier/annika/HASPECT6/hsfit/sPlot.C";

#endif
